# Generated by Django 3.2.14 on 2022-07-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('money', models.IntegerField(default=0)),
                ('auto_in', models.CharField(max_length=150)),
            ],
        ),
    ]
