# Generated by Django 3.2.14 on 2022-07-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220726_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
                ('disc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity_in_stock', models.IntegerField()),
            ],
        ),
    ]
