# Generated by Django 3.2.14 on 2022-07-27 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20220727_0441'),
    ]

